language: node_js
node_js: "0.10"
services:
  - redis-server

before_install:
  # Download the bleeding edge tesseract.
  - "curl -L https://github.com/elliotchance/tesseract/archive/master.zip > tesseract.zip"
  - "unzip tesseract.zip"
  - "sudo pip install -r tesseract-master/requirements.txt"

  # Start tesseract server.
  - "tesseract-master/bin/tesseract &"

script:
  # Run unit tests.
  - node_modules/.bin/nodeunit test

  # Lint JavaScript.
  - node_modules/.bin/jshint src
